import type { ConcertCategory, TaxiPot } from "./types";

export const defaultCategories: ConcertCategory[] = [
  {
    id: "xdinary-heroes-xcape",
    slug: "xdinary-heroes-xcape",
    title: "Xdinary Heroes 2026 Summer Special <The Xcape>",
    sortOrder: 1,
    isActive: true,
    keywords: ["xdinary", "heroes", "xcape"],
    excludedKeywords: [],
  },
  {
    id: "babymonster-choom",
    slug: "babymonster-choom",
    title: "2026-27 BABYMONSTER WORLD TOUR [춤 (CHOOM)] IN SEOUL",
    sortOrder: 2,
    isActive: true,
    keywords: ["babymonster", "choom"],
    excludedKeywords: [],
  },
  {
    id: "andteam-blaze",
    slug: "andteam-blaze",
    title: "2026 &TEAM CONCERT TOUR 'BLAZE THE WAY' in INCHEON",
    sortOrder: 3,
    isActive: true,
    keywords: ["&team", "andteam", "blaze"],
    excludedKeywords: [],
  },
  {
    id: "tws-247",
    slug: "tws-247",
    title: "2026 TWS TOUR '24/7:FOR:YOU' IN SEOUL",
    sortOrder: 4,
    isActive: true,
    keywords: ["tws", "24/7:for:you"],
    excludedKeywords: [],
  },
  {
    id: "other",
    slug: "other",
    title: "기타",
    sortOrder: 999,
    isActive: true,
    keywords: [],
    excludedKeywords: [],
  },
];

export const initialTaxiPots: TaxiPot[] = [
  {
    id: "taxi-pot-1",
    categoryId: "xdinary-heroes-xcape",
    concertTitle: "Xdinary Heroes 2026 Summer Special <The Xcape>",
    origin: "운서역",
    destination: "인스파이어 아레나",
    date: "2026-06-27",
    time: "14:00",
    openChatUrl: "https://open.kakao.com/",
  },
  {
    id: "taxi-pot-2",
    categoryId: "xdinary-heroes-xcape",
    concertTitle: "Xdinary Heroes 2026 Summer Special <The Xcape>",
    origin: "인천국제공항T1",
    destination: "인스파이어 아레나",
    date: "2026-06-27",
    time: "14:30",
    openChatUrl: "https://open.kakao.com/",
  },
  {
    id: "taxi-pot-3",
    categoryId: "xdinary-heroes-xcape",
    concertTitle: "Xdinary Heroes 2026 Summer Special <The Xcape>",
    origin: "인스파이어 아레나",
    destination: "서울역",
    date: "2026-06-27",
    time: "21:30",
    openChatUrl: "https://open.kakao.com/",
  },
];
